version: "3"


services:
  database-api:
    build: 
      context: .
      dockerfile: ./fuelControlDatabaseService/database.service.dockerfile
    ports:
      - 8080:8080
  
  web:
    build:
      context: .
      dockerfile: ./fuelControlWeb/web.dockerfile
    ports:
      - 7000:8000